name: "Azure Blob Storage - Download Blob"
description: "Download a blob from azure blob storage"
author: "Arman Rahman"
branding:
  icon: "download-cloud"
  color: "blue"
inputs:
  connection-string:
    description: "Connection string"
    required: true
  name:
    description: "Blob name"
    required: true
  path:
    description: "Destination path"
    required: false
    default: ""
  container:
    description: "Container name"
    required: false
    default: "github-action-artifacts"
runs:
  using: "node12"
  main: "dist/index.js"
