name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download with connection string
        uses: ./
        with:
          connection-string: ${{ secrets.CONNECTION_STRING }}
          container-name: "test-files"
          blob-name: "test1.txt"
          download-path: "."
      - name: Confirm
        shell: bash
        run: |
          ls
          test -f test1.txt
          rm test1.txt
      - name: Download with storage key
        uses: ./
        with:
          storage-account-name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storage-account-key: ${{ secrets.STORAGE_ACCOUNT_KEY }}
          container-name: "test-files"
          blob-name: "test1.txt"
          download-path: "."
      - name: Confirm
        shell: bash
        run: |
          ls
          test -f test1.txt
          rm test1.txt
      - name: Download with sas
        uses: ./
        with:
          storage-account-name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          sas: ${{ secrets.SAS }}
          container-name: "test-files"
          blob-name: "test1.txt"
          download-path: "."
      - name: Confirm
        shell: bash
        run: |
          ls
          test -f test1.txt
          rm test1.txt
      - name: Download with creds
        uses: ./
        with:
          storage-account-name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          container-name: "test-files"
          blob-name: "test1.txt"
          download-path: "."
      - name: Confirm
        shell: bash
        run: |
          ls
          test -f test1.txt
          rm test1.txt
      - name: Download with env variables
        uses: ./
        with:
          storage-account-name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          container-name: "test-files"
          blob-name: "test1.txt"
          download-path: "."
        env: # Or as an environment variable
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Confirm
        shell: bash
        run: |
          ls
          test -f test1.txt
          rm test1.txt
